sudo: required

language: python

services:
  - docker

before_script:
  - docker build -t mozi/snet_service .
  - docker run -it mozi/snet_service /bin/bash -c "coverage run --rcfile=./.coveragerc -m unittest && coverage report"

script:
  - pip install codecov
  - codecov