sudo: required

language: python

services:
  - docker

before_script:
  - docker-compose up -d
  - docker exec moses_snet_service sh -c "pip install codecov"

script:
  - docker exec moses_snet_service sh -c "coverage run --rcfile=./.coveragerc -m unittest && coverage report"
  - docker exec moses_snet_service sh -c "codecov"