version: "3"
services:
  moses_service:
      build: ./
      container_name: moses-service
      links:
        - mongo
        - redis
        - frontend
      ports:
          - "5003:5003"
          - "5000:5000"
          - "5002:5002"

      environment:
          - MONGODB_URI=mongodb://mongo:27017/
          - DATASETS_DIR=/home/root/datasets
          - REDIS_URI=redis://redis:6379/0
          - USER=root
          - EXPIRY_SPAN=14
          - SCAN_INTERVAL=86400
          - APP_PORT=$APP_PORT
          - SERVICE_ADDR=$SERVICE_ADDR

      working_dir: /home/root/mozi_snet_service

      command: bash -c "circusd --log-level debug circus.ini"

  frontend:
      build:
          context: result_ui/
          args:
            - SERVER_ADDR=$SERVICE_ADDR

      container_name: result-ui

      ports:
          - $APP_PORT:80
  mongo:
      image: mongo

  redis:
      image: redis
