version: "3"
services:
  moses_service:
      image: xabush/moses_snet_service
      container_name: moses_service
      links:
        - mongo
        - redis
        - frontend
      ports:
          - "5003:5003"
          - "5000:5000"

      environment:
          - MONGODB_URI=mongodb://mongo:27017/
          - DATASETS_DIR=/home/root/datasets
          - REDIS_URI=redis://redis:6379/0
          - USER=root
          - EXPIRY_SPAN=${EXPIRY_SPAN}
          - SCAN_INTERVAL=${SCAN_INTERVAL}
          - APP_PORT=${APP_PORT}
          - SERVER_ADDR=${SERVER_ADDR}

      working_dir: /home/root/mozi_snet_service

      command: bash -c "circusd --log-level debug circus.ini"

  frontend:
      image: xabush/snet_react_app
      container_name: react-app

      environment:
          - SERVER_ADDR=${SERVER_ADDR}
      ports:
          - ${APP_PORT}:80
  mongo:
      image: mongo

  redis:
      image: redis
