version: 2
jobs:
    build:
        machine: true
        environment:
            -   container: moses_service
        working_directory: ~/mozi_snet_service
        steps:
            - checkout
            - run:
                  name: Start the containers
                  command: docker-compose up -d
            - run:
                  name: Run tests
                  command: docker exec $container sh -c "coverage run --rcfile=./.coveragerc -m unittest && coverage report"


workflows:
    version: 2
    build_and_test:
        jobs:
            - build