version: 2

jobs:
    build:
        machine: true
        environment:
            - container: moses_service
        working_directory: ~/mozi_snet_service
        steps:
            - checkout
            - run:
                 name: Build images
                 command: docker-compose -f docker-compose-dev.yml
            - run:
                  name: Start the containers
                  command: docker-compose up -d
            - run:
                  name: Run tests with coverage
                  command: docker exec -it -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN $container sh -c "coverage run --rcfile=./.coveragerc -m unittest && coverage report && coveralls"
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
