version: 2

jobs:
    build:
        machine: true
        environment:
            - container: moses_service
            - CODECOV_TOKEN: 13a8c69b-b9c8-4c0c-8682-92b9aeda97a3
        working_directory: ~/mozi_snet_service
        steps:
            - checkout
            - run:
                  name: Start the containers
                  command: docker-compose up -d
            - run:
                  name: Run tests
                  command: docker exec -it $container sh -c "coverage run --rcfile=./.coveragerc -m unittest && coverage report"

            - run:
                  name: Upload coverage report
                  command: docker exec -it $container sh - c "curl -s https://codecov.io/bash | bash"

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
