version: 2
jobs:
    build:
        machine: true
        working_directory: ~/mozi_snet_service
        steps:
            - checkout
            - run:
                name: Build docker
                command: docker-compose build .

            - run:
                  name: Start the containers
                  command: docker-compose up -d

    test:
        machine: true
        environment:
            - container: moses_snet_service
        working_directory: ~/mozi_snet_service
        steps:
            - run:
                  name: Connect to the container
                  command: docker exec $container sh -c "coverage run --rcfile=./.coveragerc -m unittest && coverage report"


workflows:
    version: 2
    jobs:
        - build
        - test:
              requires:
                  - build